#!/usr/bin/env python3

import shutil

try:
    shutil.rmtree('minimal/cluster')
except FileNotFoundError:
    pass

text = '''---\nlayout: default\n---\n
Catalogen generates a catalog of code examples collected from OSS projects.

### Techniques

1. Code Example Collection
2. Code Example Categorization
3. Code Comment generation

### Data Sources

* Source codes are hosted on [searchcode.com](https://searchcode.com)
* Code Comments are generated by Java methods and their [Javadoc](https://poi.apache.org/apidocs/overview-summary.html) comments

---

#### Members
> Daiki Takata, Maipradit Rungroj, Hideaki Hata, Takashi Ishio and Kenichi Matsumoto:
> Nara Institute of Science and Technology (Japan)
>
> Abdulaziz Alhefdhi, Hoa Khanh Dam: 
> University of Wollongong (Australia)
'''

with open('minimal/index.md', 'w') as f:
    f.write(text)
