package domain.system;

import java.io.Serializable;

public class Columns implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.TABLE_CATALOG
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String tableCatalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.TABLE_SCHEMA
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String tableSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.TABLE_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.COLUMN_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.ORDINAL_POSITION
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private Long ordinalPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.IS_NULLABLE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String isNullable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.DATA_TYPE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private Long characterMaximumLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private Long characterOctetLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.NUMERIC_PRECISION
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private Long numericPrecision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.NUMERIC_SCALE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private Long numericScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.CHARACTER_SET_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String characterSetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.COLLATION_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String collationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.COLUMN_KEY
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String columnKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.EXTRA
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.PRIVILEGES
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String privileges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema..COLUMNS.COLUMN_COMMENT
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private String columnComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table information_schema..COLUMNS
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.TABLE_CATALOG
     *
     * @return the value of information_schema..COLUMNS.TABLE_CATALOG
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getTableCatalog() {
        return tableCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.TABLE_CATALOG
     *
     * @param tableCatalog the value for information_schema..COLUMNS.TABLE_CATALOG
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog == null ? null : tableCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.TABLE_SCHEMA
     *
     * @return the value of information_schema..COLUMNS.TABLE_SCHEMA
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.TABLE_SCHEMA
     *
     * @param tableSchema the value for information_schema..COLUMNS.TABLE_SCHEMA
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema == null ? null : tableSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.TABLE_NAME
     *
     * @return the value of information_schema..COLUMNS.TABLE_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.TABLE_NAME
     *
     * @param tableName the value for information_schema..COLUMNS.TABLE_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.COLUMN_NAME
     *
     * @return the value of information_schema..COLUMNS.COLUMN_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.COLUMN_NAME
     *
     * @param columnName the value for information_schema..COLUMNS.COLUMN_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.ORDINAL_POSITION
     *
     * @return the value of information_schema..COLUMNS.ORDINAL_POSITION
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public Long getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.ORDINAL_POSITION
     *
     * @param ordinalPosition the value for information_schema..COLUMNS.ORDINAL_POSITION
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setOrdinalPosition(Long ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.IS_NULLABLE
     *
     * @return the value of information_schema..COLUMNS.IS_NULLABLE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getIsNullable() {
        return isNullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.IS_NULLABLE
     *
     * @param isNullable the value for information_schema..COLUMNS.IS_NULLABLE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setIsNullable(String isNullable) {
        this.isNullable = isNullable == null ? null : isNullable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.DATA_TYPE
     *
     * @return the value of information_schema..COLUMNS.DATA_TYPE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.DATA_TYPE
     *
     * @param dataType the value for information_schema..COLUMNS.DATA_TYPE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @return the value of information_schema..COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public Long getCharacterMaximumLength() {
        return characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @param characterMaximumLength the value for information_schema..COLUMNS.CHARACTER_MAXIMUM_LENGTH
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @return the value of information_schema..COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public Long getCharacterOctetLength() {
        return characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @param characterOctetLength the value for information_schema..COLUMNS.CHARACTER_OCTET_LENGTH
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.NUMERIC_PRECISION
     *
     * @return the value of information_schema..COLUMNS.NUMERIC_PRECISION
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public Long getNumericPrecision() {
        return numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.NUMERIC_PRECISION
     *
     * @param numericPrecision the value for information_schema..COLUMNS.NUMERIC_PRECISION
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setNumericPrecision(Long numericPrecision) {
        this.numericPrecision = numericPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.NUMERIC_SCALE
     *
     * @return the value of information_schema..COLUMNS.NUMERIC_SCALE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public Long getNumericScale() {
        return numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.NUMERIC_SCALE
     *
     * @param numericScale the value for information_schema..COLUMNS.NUMERIC_SCALE
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setNumericScale(Long numericScale) {
        this.numericScale = numericScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.CHARACTER_SET_NAME
     *
     * @return the value of information_schema..COLUMNS.CHARACTER_SET_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.CHARACTER_SET_NAME
     *
     * @param characterSetName the value for information_schema..COLUMNS.CHARACTER_SET_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName == null ? null : characterSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.COLLATION_NAME
     *
     * @return the value of information_schema..COLUMNS.COLLATION_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getCollationName() {
        return collationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.COLLATION_NAME
     *
     * @param collationName the value for information_schema..COLUMNS.COLLATION_NAME
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setCollationName(String collationName) {
        this.collationName = collationName == null ? null : collationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.COLUMN_KEY
     *
     * @return the value of information_schema..COLUMNS.COLUMN_KEY
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getColumnKey() {
        return columnKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.COLUMN_KEY
     *
     * @param columnKey the value for information_schema..COLUMNS.COLUMN_KEY
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setColumnKey(String columnKey) {
        this.columnKey = columnKey == null ? null : columnKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.EXTRA
     *
     * @return the value of information_schema..COLUMNS.EXTRA
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.EXTRA
     *
     * @param extra the value for information_schema..COLUMNS.EXTRA
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.PRIVILEGES
     *
     * @return the value of information_schema..COLUMNS.PRIVILEGES
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getPrivileges() {
        return privileges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.PRIVILEGES
     *
     * @param privileges the value for information_schema..COLUMNS.PRIVILEGES
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setPrivileges(String privileges) {
        this.privileges = privileges == null ? null : privileges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema..COLUMNS.COLUMN_COMMENT
     *
     * @return the value of information_schema..COLUMNS.COLUMN_COMMENT
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public String getColumnComment() {
        return columnComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema..COLUMNS.COLUMN_COMMENT
     *
     * @param columnComment the value for information_schema..COLUMNS.COLUMN_COMMENT
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    public void setColumnComment(String columnComment) {
        this.columnComment = columnComment == null ? null : columnComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema..COLUMNS
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Columns other = (Columns) that;
        return (this.getTableCatalog() == null ? other.getTableCatalog() == null : this.getTableCatalog().equals(other.getTableCatalog()))
            && (this.getTableSchema() == null ? other.getTableSchema() == null : this.getTableSchema().equals(other.getTableSchema()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()))
            && (this.getColumnName() == null ? other.getColumnName() == null : this.getColumnName().equals(other.getColumnName()))
            && (this.getOrdinalPosition() == null ? other.getOrdinalPosition() == null : this.getOrdinalPosition().equals(other.getOrdinalPosition()))
            && (this.getIsNullable() == null ? other.getIsNullable() == null : this.getIsNullable().equals(other.getIsNullable()))
            && (this.getDataType() == null ? other.getDataType() == null : this.getDataType().equals(other.getDataType()))
            && (this.getCharacterMaximumLength() == null ? other.getCharacterMaximumLength() == null : this.getCharacterMaximumLength().equals(other.getCharacterMaximumLength()))
            && (this.getCharacterOctetLength() == null ? other.getCharacterOctetLength() == null : this.getCharacterOctetLength().equals(other.getCharacterOctetLength()))
            && (this.getNumericPrecision() == null ? other.getNumericPrecision() == null : this.getNumericPrecision().equals(other.getNumericPrecision()))
            && (this.getNumericScale() == null ? other.getNumericScale() == null : this.getNumericScale().equals(other.getNumericScale()))
            && (this.getCharacterSetName() == null ? other.getCharacterSetName() == null : this.getCharacterSetName().equals(other.getCharacterSetName()))
            && (this.getCollationName() == null ? other.getCollationName() == null : this.getCollationName().equals(other.getCollationName()))
            && (this.getColumnKey() == null ? other.getColumnKey() == null : this.getColumnKey().equals(other.getColumnKey()))
            && (this.getExtra() == null ? other.getExtra() == null : this.getExtra().equals(other.getExtra()))
            && (this.getPrivileges() == null ? other.getPrivileges() == null : this.getPrivileges().equals(other.getPrivileges()))
            && (this.getColumnComment() == null ? other.getColumnComment() == null : this.getColumnComment().equals(other.getColumnComment()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema..COLUMNS
     *
     * @mbggenerated Thu Nov 28 11:28:37 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTableCatalog() == null) ? 0 : getTableCatalog().hashCode());
        result = prime * result + ((getTableSchema() == null) ? 0 : getTableSchema().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        result = prime * result + ((getColumnName() == null) ? 0 : getColumnName().hashCode());
        result = prime * result + ((getOrdinalPosition() == null) ? 0 : getOrdinalPosition().hashCode());
        result = prime * result + ((getIsNullable() == null) ? 0 : getIsNullable().hashCode());
        result = prime * result + ((getDataType() == null) ? 0 : getDataType().hashCode());
        result = prime * result + ((getCharacterMaximumLength() == null) ? 0 : getCharacterMaximumLength().hashCode());
        result = prime * result + ((getCharacterOctetLength() == null) ? 0 : getCharacterOctetLength().hashCode());
        result = prime * result + ((getNumericPrecision() == null) ? 0 : getNumericPrecision().hashCode());
        result = prime * result + ((getNumericScale() == null) ? 0 : getNumericScale().hashCode());
        result = prime * result + ((getCharacterSetName() == null) ? 0 : getCharacterSetName().hashCode());
        result = prime * result + ((getCollationName() == null) ? 0 : getCollationName().hashCode());
        result = prime * result + ((getColumnKey() == null) ? 0 : getColumnKey().hashCode());
        result = prime * result + ((getExtra() == null) ? 0 : getExtra().hashCode());
        result = prime * result + ((getPrivileges() == null) ? 0 : getPrivileges().hashCode());
        result = prime * result + ((getColumnComment() == null) ? 0 : getColumnComment().hashCode());
        return result;
    }
}