/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FGoneGoods.java
 *
 * Created on Sep 20, 2009, 10:11:13 AM
 */

package Forms;

import ClassModules.Building;
import ClassModules.CargoShip;
import Modules.BuildingIdx;
import Modules.FBldgInfoIdx1;
import Modules.GoodStoreFIdx;
import Modules.ResourceIdx;
import Modules.Utilities;
import java.util.EnumSet;
import static Modules.Constants.*;
import static Modules.PRGameData.*;
import static Modules.Text1Idx.*;
import static Modules.ResourceIdx.*;

/**
 *
 * @author steve
 */
public class FGoneGoods extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;

    /** Creates new form FGoneGoods */
    public FGoneGoods(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      Frames[0] = jPanel1;
      Frames[1] = jPanel2;
      Frames[2] = jPanel3;
      Frames[3] = jPanel4;
      Option[0] = jRadioButton1;
      Option[1] = jRadioButton2;
      Option[2] = jRadioButton3;
      Option[3] = jRadioButton4;
      Option[4] = jRadioButton5;
      Option[5] = jRadioButton6;
      Option[6] = jRadioButton7;
      Option[7] = jRadioButton8;
      Option[8] = jRadioButton9;
      Option[9] = jRadioButton10;
      Option[10] = jRadioButton11;
      Option[11] = jRadioButton12;
      Option[12] = jRadioButton13;
      Option[13] = jRadioButton14;
      Option[14] = jRadioButton15;
      Option[15] = jRadioButton16;
      Option[16] = jRadioButton17;
      Option[17] = jRadioButton18;
      Option[18] = jRadioButton19;
      Option[19] = jRadioButton20;
//      This group is a dummy group used to clear the button group & sync across frames
      SyncButtons[0] = jRadioButton21;
      SyncButtons[1] = jRadioButton22;
      SyncButtons[2] = jRadioButton23;
      SyncButtons[3] = jRadioButton24;
      jRadioButton21.setVisible(false);
      jRadioButton22.setVisible(false);
      jRadioButton23.setVisible(false);
      jRadioButton24.setVisible(false);
      Good[0] = jTextField1;
      Good[1] = jTextField2;
      Good[2] = jTextField3;
      Good[3] = jTextField4;
      Good[4] = jTextField5;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                buttonGroup2 = new javax.swing.ButtonGroup();
                buttonGroup3 = new javax.swing.ButtonGroup();
                buttonGroup4 = new javax.swing.ButtonGroup();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jTextField4 = new javax.swing.JTextField();
                jTextField5 = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                jRadioButton1 = new javax.swing.JRadioButton();
                jRadioButton2 = new javax.swing.JRadioButton();
                jRadioButton3 = new javax.swing.JRadioButton();
                jRadioButton4 = new javax.swing.JRadioButton();
                jRadioButton5 = new javax.swing.JRadioButton();
                jTextField6 = new javax.swing.JTextField();
                jRadioButton21 = new javax.swing.JRadioButton();
                jPanel2 = new javax.swing.JPanel();
                jRadioButton6 = new javax.swing.JRadioButton();
                jRadioButton7 = new javax.swing.JRadioButton();
                jRadioButton8 = new javax.swing.JRadioButton();
                jRadioButton9 = new javax.swing.JRadioButton();
                jRadioButton10 = new javax.swing.JRadioButton();
                jTextField7 = new javax.swing.JTextField();
                jRadioButton22 = new javax.swing.JRadioButton();
                jPanel3 = new javax.swing.JPanel();
                jRadioButton11 = new javax.swing.JRadioButton();
                jRadioButton12 = new javax.swing.JRadioButton();
                jRadioButton13 = new javax.swing.JRadioButton();
                jRadioButton14 = new javax.swing.JRadioButton();
                jRadioButton15 = new javax.swing.JRadioButton();
                jTextField8 = new javax.swing.JTextField();
                jRadioButton23 = new javax.swing.JRadioButton();
                jPanel4 = new javax.swing.JPanel();
                jRadioButton16 = new javax.swing.JRadioButton();
                jRadioButton17 = new javax.swing.JRadioButton();
                jRadioButton18 = new javax.swing.JRadioButton();
                jRadioButton19 = new javax.swing.JRadioButton();
                jRadioButton20 = new javax.swing.JRadioButton();
                jTextField9 = new javax.swing.JTextField();
                jRadioButton24 = new javax.swing.JRadioButton();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(469, 325));
                setResizable(false);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jTextField1.setBackground(new java.awt.Color(0, 0, 255));
                jTextField1.setEditable(false);
                jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField1.setForeground(new java.awt.Color(255, 255, 255));
                jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField1.setText("0");
                getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

                jTextField2.setBackground(new java.awt.Color(254, 255, 255));
                jTextField2.setEditable(false);
                jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField2.setForeground(new java.awt.Color(51, 51, 51));
                jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField2.setText("0");
                getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, -1));

                jTextField3.setBackground(new java.awt.Color(255, 255, 0));
                jTextField3.setEditable(false);
                jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField3.setForeground(new java.awt.Color(51, 51, 51));
                jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField3.setText("0");
                getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 40, -1));

                jTextField4.setBackground(new java.awt.Color(204, 153, 0));
                jTextField4.setEditable(false);
                jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField4.setForeground(new java.awt.Color(51, 51, 51));
                jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField4.setText("0");
                getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, -1));

                jTextField5.setBackground(new java.awt.Color(102, 51, 0));
                jTextField5.setEditable(false);
                jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
                jTextField5.setForeground(new java.awt.Color(255, 255, 255));
                jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField5.setText("0");
                getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 40, -1));

                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buttonGroup1.add(jRadioButton1);
                jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton1MouseReleased(evt);
                        }
                });
                jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

                buttonGroup1.add(jRadioButton2);
                jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton2MouseReleased(evt);
                        }
                });
                jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, -1, -1));

                buttonGroup1.add(jRadioButton3);
                jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton3MouseReleased(evt);
                        }
                });
                jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

                buttonGroup1.add(jRadioButton4);
                jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton4MouseReleased(evt);
                        }
                });
                jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 180, -1, -1));

                buttonGroup1.add(jRadioButton5);
                jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton5MouseReleased(evt);
                        }
                });
                jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                jTextField6.setEditable(false);
                jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField6.setText("Store 1 Good");
                jTextField6.setOpaque(false);
                jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

                buttonGroup1.add(jRadioButton21);
                jPanel1.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 115, 270));

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel2.setVerifyInputWhenFocusTarget(false);
                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buttonGroup2.add(jRadioButton6);
                jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton6MouseReleased(evt);
                        }
                });
                jPanel2.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

                buttonGroup2.add(jRadioButton7);
                jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton7MouseReleased(evt);
                        }
                });
                jPanel2.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, -1, -1));

                buttonGroup2.add(jRadioButton8);
                jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton8MouseReleased(evt);
                        }
                });
                jPanel2.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

                buttonGroup2.add(jRadioButton9);
                jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton9MouseReleased(evt);
                        }
                });
                jPanel2.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 180, -1, -1));

                buttonGroup2.add(jRadioButton10);
                jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton10MouseReleased(evt);
                        }
                });
                jPanel2.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                jTextField7.setEditable(false);
                jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField7.setText("Small Warehouse");
                jTextField7.setOpaque(false);
                jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

                buttonGroup2.add(jRadioButton22);
                jPanel2.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 115, 270));

                jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buttonGroup3.add(jRadioButton11);
                jRadioButton11.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton11MouseReleased(evt);
                        }
                });
                jPanel3.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

                buttonGroup3.add(jRadioButton12);
                jRadioButton12.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton12MouseReleased(evt);
                        }
                });
                jPanel3.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, -1, -1));

                buttonGroup3.add(jRadioButton13);
                jRadioButton13.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton13MouseReleased(evt);
                        }
                });
                jPanel3.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

                buttonGroup3.add(jRadioButton14);
                jRadioButton14.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton14MouseReleased(evt);
                        }
                });
                jPanel3.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 180, -1, -1));

                buttonGroup3.add(jRadioButton15);
                jRadioButton15.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton15MouseReleased(evt);
                        }
                });
                jPanel3.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                jTextField8.setEditable(false);
                jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField8.setText("Large Warehouse");
                jTextField8.setOpaque(false);
                jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

                buttonGroup3.add(jRadioButton23);
                jPanel3.add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 115, 270));

                jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buttonGroup4.add(jRadioButton16);
                jRadioButton16.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton16MouseReleased(evt);
                        }
                });
                jPanel4.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

                buttonGroup4.add(jRadioButton17);
                jRadioButton17.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton17MouseReleased(evt);
                        }
                });
                jPanel4.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, -1, -1));

                buttonGroup4.add(jRadioButton18);
                jRadioButton18.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton18MouseReleased(evt);
                        }
                });
                jPanel4.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

                buttonGroup4.add(jRadioButton19);
                jRadioButton19.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton19MouseReleased(evt);
                        }
                });
                jPanel4.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 180, -1, -1));

                buttonGroup4.add(jRadioButton20);
                jRadioButton20.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jRadioButton20MouseReleased(evt);
                        }
                });
                jPanel4.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                jTextField9.setEditable(false);
                jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField9.setText("Large Warehouse");
                jTextField9.setOpaque(false);
                jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 105, -1));

                buttonGroup4.add(jRadioButton24);
                jPanel4.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 230, -1, -1));

                getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 115, 270));

                jButton1.setText("OK");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton1MouseReleased

    private void jRadioButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton2MouseReleased

    private void jRadioButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton3MouseReleased

    private void jRadioButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton4MouseReleased

    private void jRadioButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton5MouseReleased

    private void jRadioButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton6MouseReleased

    private void jRadioButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton7MouseReleased

    private void jRadioButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton8MouseReleased

    private void jRadioButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton9MouseReleased

    private void jRadioButton10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton10MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton10MouseReleased

    private void jRadioButton11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton11MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton11MouseReleased

    private void jRadioButton12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton12MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton12MouseReleased

    private void jRadioButton13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton13MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton13MouseReleased

    private void jRadioButton14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton14MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton14MouseReleased

    private void jRadioButton15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton15MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton15MouseReleased

    private void jRadioButton16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton16MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton16MouseReleased

    private void jRadioButton17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton17MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton17MouseReleased

    private void jRadioButton18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton18MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton18MouseReleased

    private void jRadioButton19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton19MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton19MouseReleased

    private void jRadioButton20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton20MouseReleased
     RadioClicked(evt);
    }//GEN-LAST:event_jRadioButton20MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 for (ResourceIdx iRR : EnumSet.range( Indigo , Coffee)){
  int iR = iRR.ordinal();
  PRFArray[PRGDCurrentPlayer.ordinal()].Text1[IndigoIdx.ordinal() + iR].setText("0");
  for (GoodStoreFIdx ig : EnumSet.range( GoodStoreFIdx.CompassGSFI , GoodStoreFIdx.LargeWH2GSFI)){
   int i = ig.ordinal();
   if ( Frames[i].isVisible() & Option[iR + i * PRCNumGoods].isVisible() )
    if ( Option[iR + i * PRCNumGoods].isSelected())
     if ( ig == GoodStoreFIdx.CompassGSFI )
      PRFArray[PRGDCurrentPlayer.ordinal()].Text1[IndigoIdx.ordinal() + iR].setText("1");
     else
      PRFArray[PRGDCurrentPlayer.ordinal()].Text1[IndigoIdx.ordinal() + iR].setText(Good[iR].getText());
  };
  PRPuertoRico.playermat.Text1[IndigoBankIdx.ordinal() + iR].setText(Integer.toString(
	  Integer.valueOf(PRPuertoRico.playermat.Text1[IndigoBankIdx.ordinal() + iR].getText())
	  + Integer.valueOf(Good[iR].getText()) - Integer.valueOf(PRFArray[PRGDCurrentPlayer.ordinal()].
	  Text1[IndigoIdx.ordinal() + iR].getText())));
 };
 CargoShip.GoodsHoused(PRGDCurrentPlayer);
 this.setVisible(false);
// PRPuertoRico.playermat.Command2.setVisible(true); = true
 PRPuertoRico.GoGoGo();
    }//GEN-LAST:event_jButton1ActionPerformed

void RadioClicked(java.awt.event.MouseEvent evt) {
// Synchronise buttons across frames
int RadioBSelected = Utilities.getControlIdx(evt); // 0 to 4 depends on which good picked
for (GoodStoreFIdx fc : EnumSet.range(GoodStoreFIdx.CompassGSFI, GoodStoreFIdx.LargeWH2GSFI)) {  // Loop across the frames
//for (GoodStoreFIdx fc = 0; fc < 4; fc++) {  // Loop across the frames
 if (this.Frames[fc.ordinal()].isAncestorOf((javax.swing.JRadioButton) evt.getSource())) {}
 else
  if (this.Option[fc.ordinal()*PRCNumResources + RadioBSelected].isSelected())
// Setting the Sync button clears the visible buttons for that frame
  this.SyncButtons[ fc.ordinal()].setSelected(true);
}
}

public void Initialise() {
 //Account for small warehouse: add a frame if necessary
 if ( Building.Production(PRGDCurrentPlayer, BuildingIdx.SmallWarehouseIdx) > 0 )
  Frames[GoodStoreFIdx.SmallWHGSFI.ordinal()].setVisible(true);
 else
  Frames[GoodStoreFIdx.SmallWHGSFI.ordinal()].setVisible(false);

 //Account for large warehouse: add frames if necessary
 if ( Building.Production(PRGDCurrentPlayer, BuildingIdx.LargeWarehouseIdx) > 0 ) {
  Frames[GoodStoreFIdx.LargeWH1GSFI.ordinal()].setVisible(true);
  Frames[GoodStoreFIdx.LargeWH2GSFI.ordinal()].setVisible(true); }
 else {
  Frames[GoodStoreFIdx.LargeWH1GSFI.ordinal()].setVisible(false);
  Frames[GoodStoreFIdx.LargeWH2GSFI.ordinal()].setVisible(false);
 };

 //Copy resources to GoneGoods form
 for (ResourceIdx iR : EnumSet.range( Indigo , Coffee)){
  Good[iR.ordinal()].setText(PRFArray[PRGDCurrentPlayer.ordinal()].Text1[IndigoIdx.ordinal() + iR.ordinal()].getText());
 };

 //appear a button for each warehouse option
 for (GoodStoreFIdx ig : EnumSet.range( GoodStoreFIdx.CompassGSFI , GoodStoreFIdx.LargeWH2GSFI)){
  int i = ig.ordinal();

// Setting the Sync button clears the visible buttons for that frame
  this.SyncButtons[ ig.ordinal()].setSelected(true);
  if ( Frames[i].isVisible() ) {
   for (ResourceIdx iRR : EnumSet.range( Indigo , Coffee)){
    int iR = iRR.ordinal();
    if ( Integer.valueOf(Good[iR].getText()) > 0 ) {
     Option[iR + i * PRCNumGoods].setVisible(true); }
    else {
     Option[iR + i * PRCNumGoods].setVisible(false);
    };
   };
  };
 };
 this.setTitle(PRGDPlayerNameStrings[PRGDCurrentPlayer.ordinal()] + " What To Do With Your Un-shipped Goods?");
};
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FGoneGoods dialog = new FGoneGoods(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.ButtonGroup buttonGroup3;
        private javax.swing.ButtonGroup buttonGroup4;
        private javax.swing.JButton jButton1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JRadioButton jRadioButton10;
        private javax.swing.JRadioButton jRadioButton11;
        private javax.swing.JRadioButton jRadioButton12;
        private javax.swing.JRadioButton jRadioButton13;
        private javax.swing.JRadioButton jRadioButton14;
        private javax.swing.JRadioButton jRadioButton15;
        private javax.swing.JRadioButton jRadioButton16;
        private javax.swing.JRadioButton jRadioButton17;
        private javax.swing.JRadioButton jRadioButton18;
        private javax.swing.JRadioButton jRadioButton19;
        private javax.swing.JRadioButton jRadioButton2;
        private javax.swing.JRadioButton jRadioButton20;
        private javax.swing.JRadioButton jRadioButton21;
        private javax.swing.JRadioButton jRadioButton22;
        private javax.swing.JRadioButton jRadioButton23;
        private javax.swing.JRadioButton jRadioButton24;
        private javax.swing.JRadioButton jRadioButton3;
        private javax.swing.JRadioButton jRadioButton4;
        private javax.swing.JRadioButton jRadioButton5;
        private javax.swing.JRadioButton jRadioButton6;
        private javax.swing.JRadioButton jRadioButton7;
        private javax.swing.JRadioButton jRadioButton8;
        private javax.swing.JRadioButton jRadioButton9;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField8;
        private javax.swing.JTextField jTextField9;
        // End of variables declaration//GEN-END:variables
private javax.swing.JPanel Frames[] = new javax.swing.JPanel[GoodStoreFIdx.LargeWH2GSFI.ordinal()+1];
private javax.swing.JRadioButton Option[] = new javax.swing.JRadioButton[
	(GoodStoreFIdx.LargeWH2GSFI.ordinal()+1)* PRCNumGoods];
private javax.swing.JTextField Good[] = new javax.swing.JTextField[PRCNumGoods];
private javax.swing.JRadioButton SyncButtons[] = 
	new javax.swing.JRadioButton[GoodStoreFIdx.LargeWH2GSFI.ordinal()+1];
}
