package hibernate;

// Generated 13.01.2008 17:44:29 by Hibernate Tools 3.2.0.b9

/**
 * Blocklist generated by hbm2java
 */
public class Blocklist implements java.io.Serializable {

	private BlocklistId id;

	public Blocklist() {
	}

	public Blocklist(BlocklistId id) {
		this.id = id;
	}

	public BlocklistId getId() {
		return this.id;
	}

	public void setId(BlocklistId id) {
		this.id = id;
	}

}
