//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 12:45:30 AM IST 
//


package com.sun.jbi.hl7bc.extservice.ack.hl7v26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v2xml}NA.1" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}NA.2" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}NA.3" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v2xml}NA.4" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NA", propOrder = {
    "na1",
    "na2",
    "na3",
    "na4"
})
public class NA {

    @XmlElement(name = "NA.1")
    protected NA1CONTENT na1;
    @XmlElement(name = "NA.2")
    protected NA2CONTENT na2;
    @XmlElement(name = "NA.3")
    protected NA3CONTENT na3;
    @XmlElement(name = "NA.4")
    protected NA4CONTENT na4;

    /**
     * Gets the value of the na1 property.
     * 
     * @return
     *     possible object is
     *     {@link NA1CONTENT }
     *     
     */
    public NA1CONTENT getNA1() {
        return na1;
    }

    /**
     * Sets the value of the na1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NA1CONTENT }
     *     
     */
    public void setNA1(NA1CONTENT value) {
        this.na1 = value;
    }

    /**
     * Gets the value of the na2 property.
     * 
     * @return
     *     possible object is
     *     {@link NA2CONTENT }
     *     
     */
    public NA2CONTENT getNA2() {
        return na2;
    }

    /**
     * Sets the value of the na2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NA2CONTENT }
     *     
     */
    public void setNA2(NA2CONTENT value) {
        this.na2 = value;
    }

    /**
     * Gets the value of the na3 property.
     * 
     * @return
     *     possible object is
     *     {@link NA3CONTENT }
     *     
     */
    public NA3CONTENT getNA3() {
        return na3;
    }

    /**
     * Sets the value of the na3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NA3CONTENT }
     *     
     */
    public void setNA3(NA3CONTENT value) {
        this.na3 = value;
    }

    /**
     * Gets the value of the na4 property.
     * 
     * @return
     *     possible object is
     *     {@link NA4CONTENT }
     *     
     */
    public NA4CONTENT getNA4() {
        return na4;
    }

    /**
     * Sets the value of the na4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NA4CONTENT }
     *     
     */
    public void setNA4(NA4CONTENT value) {
        this.na4 = value;
    }

}
